name: Bump known vars

on:
  schedule:
    # Saturday 4:30am
    - cron: "30 4 * * 6"
  workflow_dispatch:

jobs:
  bumpvar:
    name: "Bump known vars"
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    if: github.repository == 'priv-kweihmann/oelint-data'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install requirements
        run: |
          sudo apt install gawk wget git diffstat unzip texinfo gcc build-essential \
               chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
               iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool \
               file locales libacl1
          sudo locale-gen en_US.UTF-8
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Bump known vars
        run: |
          for branch in kirkstone scarthgap styhead master; do
            ${GITHUB_WORKSPACE}/scripts/bump-vars $branch
          done
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          reviewers: priv-kweihmann
          branch: "chore/dataupdate"
          commit-message: "data: bump latest known variables"
          title: "data: bump latest known variables"
          body: "auto generated data update"
          add-paths: |
            oelint_data/*.json
            scripts/bump-vars.config.json
